const styles = {
  landingPage: {
    minHeight: "100vh",
    backgroundColor: "#f7f8fa",
    padding: "28px",
    boxSizing: "border-box",
    fontFamily:
      "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    color: "#111111",
    textAlign: "left",
    position: "relative",
    overflow: "hidden",
  },
  landingHeader: {
    width: "calc(100vw - 40px)",
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
    position: "relative",
    zIndex: 3,
  },
  brand: {
    margin: 0,
    fontSize: "15px",
    fontWeight: 800,
    color: "#303841",
  },
  loginButton: {
    border: "1px solid #d3d8de",
    borderRadius: "999px",
    padding: "8px 14px",
    backgroundColor: "#303841",
    color: "white",
    fontSize: "13px",
    fontWeight: 800,
    cursor: "pointer",
    boxShadow: "none",
  },
  floatingRecord: {
    position: "absolute",
    width: "560px",
    minHeight: "760px",
    borderRadius: "22px",
    padding: "38px",
    backgroundColor: "rgba(255, 255, 255, 0.76)",
    border: "1px solid rgba(19, 185, 174, 0.18)",
    boxShadow: "none",
    filter: "blur(2px)",
    opacity: 0.32,
    color: "#1a1a1a",
    boxSizing: "border-box",
    pointerEvents: "none",
    zIndex: 1,
  },
  floatingRecordCenter: {
    position: "absolute",
    width: "520px",
    minHeight: "700px",
    borderRadius: "22px",
    padding: "34px",
    backgroundColor: "rgba(255, 255, 255, 0.54)",
    border: "1px solid rgba(35, 134, 215, 0.12)",
    boxShadow: "none",
    filter: "blur(2.5px)",
    opacity: 0.2,
    color: "#1a1a1a",
    boxSizing: "border-box",
    pointerEvents: "none",
    zIndex: 1,
  },
  recordSheetTitle: {
    margin: "0 0 18px",
    fontSize: "30px",
    fontWeight: 900,
    color: "#0a0a0a",
  },
  recordSheetLine: {
    margin: "0 0 13px",
    fontSize: "16px",
    lineHeight: 1.7,
    fontWeight: 700,
    wordBreak: "keep-all",
  },
  centerStage: {
    maxWidth: "740px",
    margin: "34px auto 0",
    position: "relative",
    zIndex: 2,
  },
  introBox: {
    padding: "46px",
    borderRadius: "28px",
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    border: "1px solid #dde1e6",
    boxShadow: "none",
    textAlign: "center",
  },
  heroLogo: {
    display: "block",
    width: "140px",
    height: "140px",
    objectFit: "contain",
    margin: "0 auto 22px",
  },
  landingFeatureRow: {
    marginTop: "18px",
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "12px",
  },
  landingFeatureCard: {
    minHeight: "118px",
    borderRadius: "18px",
    padding: "20px",
    backgroundColor: "#303841",
    border: "1px solid #dde1e6",
    boxShadow: "none",
    boxSizing: "border-box",
  },
  landingFeatureTitle: {
    display: "block",
    marginBottom: "10px",
    color: "#d3d8de",
    fontSize: "17px",
    fontWeight: 900,
  },
  landingFeatureText: {
    display: "block",
    color: "#e7eaee",
    fontSize: "14px",
    lineHeight: 1.6,
    fontWeight: 700,
    wordBreak: "keep-all",
  },
  kicker: {
    margin: "0 0 14px",
    color: "#737d88",
    fontSize: "14px",
    fontWeight: 900,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  heroTitle: {
    margin: 0,
    color: "#303841",
    fontSize: "42px",
    lineHeight: 1.18,
    fontWeight: 900,
  },
  heroText: {
    margin: "24px auto 0",
    color: "#59616b",
    fontSize: "22px",
    lineHeight: 1.75,
    fontWeight: 800,
    wordBreak: "keep-all",
  },
  page: {
    minHeight: "100vh",
    backgroundColor: "#f7f8fa",
    backgroundImage: "none",
    backgroundSize: "auto, 36px 36px, 36px 36px, auto",
    backgroundRepeat: "no-repeat, repeat, repeat, no-repeat",
    backgroundPosition: "0 0, 0 0, 0 0, 0 0",
    padding: "48px 24px",
    boxSizing: "border-box",
    fontFamily:
      "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    color: "#303841",
    overflowX: "hidden",
    position: "relative",
    isolation: "isolate",
  },
  card: {
    maxWidth: "960px",
    margin: "0 auto",
    backgroundColor: "rgba(255, 255, 255, 0.94)",
    border: "1px solid rgba(255, 255, 255, 0.86)",
    borderRadius: "28px",
    padding: "36px",
    boxShadow: "none",
    backdropFilter: "blur(10px)",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    gap: "20px",
    alignItems: "flex-start",
  },
  headerActions: {
    display: "flex",
    gap: "10px",
    alignItems: "center",
    flexWrap: "wrap",
  },
  headerButton: {
    border: "1px solid #dde1e6",
    borderRadius: "999px",
    padding: "12px 16px",
    backgroundColor: "rgba(255, 255, 255, 0.86)",
    color: "#303841",
    fontWeight: 900,
    cursor: "pointer",
    fontSize: "14px",
    boxShadow: "none",
  },
  logoutButton: {
    transition: "0.15s ease",
  },
  logoutButtonHover: {
    border: "1px solid #dc2626",
    backgroundColor: "#dc2626",
    color: "white",
  },
  title: {
    margin: 0,
    fontSize: "30px",
    color: "#303841",
    fontWeight: 900,
  },
  subTitle: {
    marginTop: 0,
    fontSize: "24px",
    color: "#303841",
    fontWeight: 900,
  },
  text: {
    margin: "8px 0 0",
    color: "#59616b",
    lineHeight: 1.7,
    fontWeight: 700,
  },
  smallText: {
    marginTop: "8px",
    fontSize: "13px",
    color: "#64748b",
    lineHeight: 1.6,
  },
  button: {
    border: "none",
    borderRadius: "14px",
    padding: "16px 20px",
    backgroundColor: "#303841",
    color: "white",
    fontWeight: 900,
    fontSize: "15px",
    cursor: "pointer",
    boxShadow: "none",
  },
  secondaryButton: {
    alignSelf: "center",
    border: "1px solid #d3d8de",
    borderRadius: "999px",
    padding: "12px 16px",
    backgroundColor: "#303841",
    color: "white",
    fontWeight: 900,
    cursor: "pointer",
    boxShadow: "none",
  },
  deleteButton: {
    marginTop: "16px",
    border: "1px solid #fecaca",
    borderRadius: "12px",
    padding: "10px 14px",
    backgroundColor: "#fef2f2",
    color: "#dc2626",
    fontWeight: 700,
    cursor: "pointer",
  },
  driveButton: {
    marginTop: "18px",
    marginBottom: "12px",
    border: "none",
    borderRadius: "14px",
    padding: "15px 20px",
    backgroundColor: "#303841",
    color: "white",
    fontWeight: 900,
    fontSize: "15px",
    cursor: "pointer",
    boxShadow: "none",
  },
  box: {
    marginTop: "28px",
    border: "1px solid #dde1e6",
    borderRadius: "22px",
    padding: "26px",
    backgroundColor: "rgba(255, 255, 255, 0.72)",
    boxShadow: "none",
  },
  driveUploadBox: {
    minHeight: "220px",
    border: "2px dashed #d3d8de",
    borderRadius: "22px",
    padding: "28px",
    backgroundColor: "#f7f8fa",
    boxShadow: "none",
    transition: "0.22s ease",
    position: "relative",
    overflow: "hidden",
  },
  driveUploadBoxActive: {
    border: "2px solid #303841",
    backgroundColor: "rgba(219, 244, 255, 0.95)",
    transform: "translateY(-2px)",
    boxShadow: "none",
  },
  selectedFileBox: {
    marginTop: "18px",
    borderRadius: "14px",
    backgroundColor: "white",
    padding: "14px 16px",
    border: "1px solid #dde1e6",
    boxShadow: "none",
  },
  form: {
    marginTop: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  row: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
  },
  field: {
    minWidth: 0,
  },
  label: {
    display: "block",
    marginBottom: "8px",
    fontWeight: 700,
    color: "#1e293b",
  },
  input: {
    width: "100%",
    boxSizing: "border-box",
    border: "1px solid #cbd5e1",
    borderRadius: "12px",
    padding: "12px",
    fontSize: "15px",
    backgroundColor: "white",
  },
  textarea: {
    width: "100%",
    boxSizing: "border-box",
    border: "1px solid #cbd5e1",
    borderRadius: "12px",
    padding: "12px",
    fontSize: "15px",
    lineHeight: 1.6,
    resize: "vertical",
    backgroundColor: "white",
  },
  message: {
    marginTop: "16px",
    color: "#303841",
    fontWeight: 900,
  },
  recordList: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  recordCard: {
    border: "1px solid #dde1e6",
    borderRadius: "18px",
    padding: "20px",
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    boxShadow: "none",
  },
  badgeRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
  },
  badge: {
    borderRadius: "999px",
    backgroundColor: "#e2e8f0",
    padding: "6px 10px",
    fontSize: "13px",
    color: "#334155",
    fontWeight: 700,
  },
  recordTitle: {
    marginBottom: 0,
    fontSize: "18px",
    color: "#303841",
    fontWeight: 900,
  },
  recordContent: {
    whiteSpace: "pre-wrap",
    color: "#334155",
    lineHeight: 1.7,
  },
  fileNameText: {
    margin: 0,
    color: "#59616b",
    fontSize: "14px",
    fontWeight: 800,
  },
  link: {
    display: "inline-block",
    marginTop: "10px",
    color: "#303841",
    fontWeight: 900,
    textDecoration: "none",
  },
  dateText: {
    marginTop: "14px",
    fontSize: "13px",
    color: "#5d7890",
    fontWeight: 700,
  },
};

export default styles;
